release-engineering/pubtools-marketplacesvm

docs/conf.py
setup.py

Fixes some URLs pointing to internal Gitlab

Fixes internal Gitlab URLs to Github URLs

---

tests/combined_push/test_combined_push.py
tests/community_push/test_community_push.py
tests/push/test_push.py

Remove the wait for 2s on `upload` tests

Make tests faster

---

docs/delete.rst
src/pubtools/_marketplacesvm/cloud_providers/aws.py
src/pubtools/_marketplacesvm/tasks/delete/command.py
tests/cloud_providers/test_provider_aws.py

Fixes CLI arg to --keep-snapshot instead of --keep-snapshots

Fixes CLI command to match pubtools-ami's call of --keep-snapshot

---

setup.py

Changes:
- Support StArMap responses on --repo in pubtools-marketplacesvm
- Accept a list of mappings in --repo
- Allow using Starmap Client Offline Mode
- Enhance the empty workflow detection
- Azure: Remove unnecessary "AZURE_PUBLISHER_NAME" 
- AzureProvider: Allow forcing push draft offers
- Flatten the community threads
- Add delete task to pubtools with support for AWS
- Community: Fix sharing accounts bug & Improve Logs

Release v1.1.0

---

.github/dependabot.yml

Use dependabot for GH Actions

---

setup.py

Changes:
- Allow using the pubtools-ami sharing accts format
- Community: Allow using beta from push item

Release v1.1.1

---

src/pubtools/_marketplacesvm/cloud_providers/aws.py
tests/cloud_providers/test_provider_aws.py

Fixes naming in RHCOS to be in line with upload naming.
Related to: SPSTRAT-373

Fixes RHCOS naming to be in line with normal upload naming.

---

requirements.txt

Bump CloudPub to v1.1.0

---

setup.py

Changes:
- CommunityPush Bugfix: enrich_mapped_items
Refers to SPSTRAT-398

Release v1.2.1

---

src/pubtools/_marketplacesvm/tasks/push/command.py

Reverts release-engineering/pubtools-marketplacesvm#53
Temporary revert for changes so we can release an emergency hotfix.

Revert "Switches from locked threads to async on publish"

---

requirements.txt
setup.py

Changes:
- Bump starmap-client to v2.0.0
- Bump cloudpub to v1.2.0
- Use StArMap APIv2 mappings
- Improve community upload logs
- CommunityPush Bugfix: enrich_mapped_items

Release v1.3.0

---

docs/common/credentials.rst
docs/common/mappings.rst

Update the tooling documentation to reflect the changes on supporting StArMap APIv2 responses only.
Refers to SPSTRAT-384

Update documentation for StArMap APIv2

---

setup.py

Changes:
- Community: Prevent null billing config on upload
- Bump cloudpub to v1.2.1
- Community: Allow a better handle of Release Type

Release v1.3.1

---

setup.py

Changes:
- Returns asyncio to publish in push. #60
- Add support for Python 3.13 #67
- Fixes some errors in deleting images. Some were trying to delete twice. #68
- Adds ami-version-template to manage custom versions. #69

Release v1.4.0

---

src/pubtools/_marketplacesvm/tasks/push/command.py

Found while looking up in the code to investigate another issue.
Better fix this horrible thing first.

Fix awful condition

---

setup.py

Changes:
- Add support for staged source
- Adds cloud_info to the pushcollector's clouds.json
- Community: Set billing type for AMI and Snapshot
- DeleteCommand: Fix delete_push_images interface
- DeleteCommand: Set invisible on RHSM first
- Allow deletion to continue if RHSM update fails
- Bump cloudimg to 1.15.0

Release v1.5.0

---

requirements.txt

Bump starmap-client to v2.1.1
Refers to SPSTRAT-457

Bump starmap-client to v2.1.1

---

requirements.txt

Bump CloudPub to v1.2.2

---

src/pubtools/_marketplacesvm/tasks/push/command.py

removes async to better control flow of publishing.

Reverts from asyncio

---

requirements.txt

Bump cloudpub to v.1.2.3

---

src/pubtools/_marketplacesvm/tasks/push/command.py

Adds more threads for publishing as it's a low CPU/RAM process. Also adds the ability to avoid collisions of marketplace + destination. This should make the publishing method a bit more smooth.
Related to: SPSTRAT-476

Gives Publish more threads to use while avoiding collision.

---

requirements.txt

Bump cloudpub to v1.3.0

---

setup.py

Changes:
- Bump `cloudpub` to `v1.3.1`

Release v1.6.1

---

tests/cloud_providers/test_provider_aws.py
tests/cloud_providers/test_provider_azure.py
tests/cloud_providers/test_provider_interface.py
tox.ini

Remove unused "type: ignore" comments

---

requirements.txt

- starmap-client>=2.2.1
- cloudpub>=1.3.2

Bump cloudpub and starmap-client

---

setup.py

Changes:
- Bump cloudpub and starmap-client
- SPSTRAT-518: Do not cache values between different mappings
- Do not collect the same push_time more time
- Remove unused "type: ignore" comments
- Update baseline tests to fix CI: pushsource

Release 1.7.0

---

setup.py

Changes:
- Azure: Pass the partial SAS arg to pre-publish

Release v1.8.1
