src/pubtools/_marketplacesvm/cloud_providers/aws.py, tests/cloud_providers/test_provider_aws.py
This commit fixes an issue with the `tags` param on `AWSService` which was sending it to `cloudimg.copy_ami` that doesn't support it.
=> Fix bug preventing to upload RHCOS images

src/pubtools/_marketplacesvm/cloud_providers/aws.py, tests/cloud_providers/test_provider_aws.py
We must send the actual EC2 image object to "tag_image" and not a string, otherwise it won't properly work.
=> FIX: Invoke "get_image_by_id" before "tag_image"

requirements.txt, setup.py
Changes:
- Bump `cloudpub` to `v0.9.3`
- Add test to push item with no destinations
- Fix bug preventing to upload RHCOS image
=> Release  v0.12.5

src/pubtools/_marketplacesvm/cloud_providers/aws.py, src/pubtools/_marketplacesvm/cloud_providers/base.py, src/pubtools/_marketplacesvm/cloud_providers/ms_azure.py, tests/cloud_providers/conftest.py, tests/cloud_providers/test_provider_azure.py, tests/combined_push/test_combined_push.py, tests/community_push/test_community_push.py, tests/push/test_push.py
Remove the leftovers of `stage_preview` feature which was used to perform a publishing with the final status as preview.
This is no longer supported and there's no need to keep its interfaces/calls in the code.
=> Completely remove stage_preview feature

src/pubtools/_marketplacesvm/cloud_providers/aws.py, tests/cloud_providers/test_provider_aws.py
Updated to include some missing data from push_item. Region will now be set even when using the default. Name will be updated to use the generated name before upload.
=> Changes name to generated name and adds region (if default) 

src/pubtools/_marketplacesvm/tasks/community_push/items.py, tests/community_push/test_enriched_pushitem.py
Since RHSM API doesn't expect an arch coming as `aarch64` we need to rename it to `arm64`, which is the expected value, whenever we receive a push item with such `release.arch` information.
Refers to SPSTRAT-317
=> CommunityWorkflow: Rename aarch64 to arm64

requirements.txt, setup.py
Changes:
- Completely remove stage_preview feature
- Changes name to generated name and adds region (if default) to push_item.
- Fix sharing accounts bug on CommunityVMPush
- Use a common sharing_accounts format for AWS
- Add volume property to Community Tests
- CommunityWorkflow: Rename aarch64 to arm64
- Bump cloudpub to v1.0.0
=> Release 1.0.0

src/pubtools/_marketplacesvm/tasks/community_push/command.py
This commit fixes a regression on community sharing accounts caused by #13
The issue in question is caused by appending the `accounts` list into `combined_accts`, leaving it as a `List[List[str]]` instead of `List[str]`.
The fix a simple one line change.
Refers to SPSTRAT-338
=> Fix regression on community sharing accounts

requirements.txt, src/pubtools/_marketplacesvm/cloud_providers/aws.py, src/pubtools/_marketplacesvm/cloud_providers/base.py, src/pubtools/_marketplacesvm/cloud_providers/ms_azure.py
During 1p tests we found out that the `AZURE_PUBLISHER_NAME` for Azure Credentials wasn't being used at all in the library's code.
After doing some tests I've confirmed this property is not required, so this commit removes it.
=> Azure: Remove unnecessary "AZURE_PUBLISHER_NAME"

src/pubtools/_marketplacesvm/cloud_providers/aws.py, src/pubtools/_marketplacesvm/cloud_providers/ms_azure.py, src/pubtools/_marketplacesvm/services/cloud.py, tests/cloud_providers/test_provider_azure.py, tests/services/test_services.py
This commit changes the `AzureProvider` by adding a new environment variable named `AZURE_ALLOW_DRAFT_PUSH` which when set to `true` will make the method `ensure_offer_is_writable` not be called during the publish process thus allowing the push to draft offers.
=> AzureProvider: Allow forcing push draft offers

docs/index.rst
Fixes the docs index.rst reference to delete. Was missing.
=> Adds index reference to delete command

src/pubtools/_marketplacesvm/tasks/community_push/command.py
This commit changes the community workflow to enrich a push item with "beta" if either the CLI argument `--beta` is passed or the incoming push item release type is marked as `beta`.
Refers to SPSTRAT-367
=> Community: Allow using beta from push item

src/pubtools/_marketplacesvm/tasks/push/command.py
This switches the publishing function to an async function. Unlocking it from threads to speed up the publishing. Since publishing generally doesn't do much but just wait around. This still returns the outputs in order similarly to threads.
=> Switches from locked threads to async on publish

requirements.txt
This commit bumps cloudpub to apply the following fix:
- Azure Hotfix: Return original SKU if Gen1 & Gen2 are set
=> Bump cloudpub to v1.2.1

src/pubtools/_marketplacesvm/cloud_providers/aws.py, src/pubtools/_marketplacesvm/tasks/push/command.py, tests/cloud_providers/test_provider_aws.py, tests/logs/combined_push/test_combined_push/test_do_advisory_push.txt, tests/logs/combined_push/test_combined_push/test_do_allowed_empty_mapping_push.txt, tests/logs/combined_push/test_combined_push/test_do_combined_push.txt, tests/logs/combined_push/test_combined_push/test_do_combined_push_fail_one_workflow[CommunityVMPush].txt, tests/logs/combined_push/test_combined_push/test_do_combined_push_overriden_destination.txt, tests/logs/combined_push/test_combined_push/test_do_marketplace_push.txt, tests/logs/push/test_push/test_do_push.txt, tests/logs/push/test_push/test_do_push_ami_correct_id.txt, tests/logs/push/test_push/test_do_push_azure_correct_sas.txt, tests/logs/push/test_push/test_not_vmi_push_item.txt, tests/logs/push/test_push/test_push_item_fail_publish.txt, tests/logs/push/test_push/test_push_item_no_mapped_arch.txt, tests/logs/push/test_push/test_push_item_rhcos_gov.txt, tests/logs/push/test_push/test_push_item_wrong_arch.txt, tests/logs/push/test_push/test_push_offline_starmap.txt, tests/logs/push/test_push/test_push_overridden_destination.txt, tests/push/test_push.py
Return asyncio to publish in push.
=> Returns asyncio to publish in push.

src/pubtools/_marketplacesvm/tasks/community_push/command.py, src/pubtools/_marketplacesvm/tasks/push/command.py
This commit includes a new property named `cloud_info` into the PushCollector's `clouds.json`.
This new property is a dictionary containing the provider's short name and it's account name.
Example:
```
[
{
"boot_mode": null,
"build": "rhel-ec2-9.4-20240605.82",
"build_info": {
"id": 3099998,
"name": "rhel-ec2",
"release": "20240605.82",
"version": "9.4"
},
"cloud_info": {
"account": "aws-na",
"provider": "aws"
},
...
}
]
```
Refers to SPSTRAT-363
=> Adds cloud_info to the pushcollector's clouds.json

src/pubtools/_marketplacesvm/tasks/community_push/command.py, tests/community_push/test_community_push.py
This commit changes the community workflow to add the tag `billing_type` into the AMI being uploaded in order to prevent `cloudimg` to seek for the image type `access` and get a resulting `hourly` or vice-versa.
Refers to SPSTRAT-451
=> CommunityWorkflow: Add billing type as custom tags

src/pubtools/_marketplacesvm/cloud_providers/aws.py, src/pubtools/_marketplacesvm/cloud_providers/base.py, src/pubtools/_marketplacesvm/cloud_providers/ms_azure.py, src/pubtools/_marketplacesvm/tasks/delete/command.py, tests/delete/test_delete.py, tests/logs/delete/test_delete/test_delete.txt, tests/logs/delete/test_delete/test_delete_ami_id_not_found_rhsm.txt, tests/logs/delete/test_delete/test_delete_bad_rhsm.txt, tests/logs/delete/test_delete/test_delete_dry_run.txt, tests/logs/delete/test_delete/test_delete_failed.txt, tests/logs/delete/test_delete/test_delete_failed_one.txt, tests/logs/delete/test_delete/test_delete_skip_build.txt
This PR introduces the following changes to the `VMDelete` command:
- DeleteCommand: Fix delete_push_images interface
- DeleteCommand: Set invisible on RHSM first
- Allow deletion to continue if RHSM update fails
Refers to SPSTRAT-454
=> Fix and Improve the DeleteCommand

src/pubtools/_marketplacesvm/cloud_providers/aws.py, tests/cloud_providers/test_provider_aws.py
Adds the wait mechanic to restricting versions. This is being added as there is a chance that a product can be locked by another version being applied when we run the restrict mechanic.
Related to: SPSTRAT-463
=> Adds a wait for product to unlock to post-publish (AWS)

src/pubtools/_marketplacesvm/tasks/community_push/command.py, tests/community_push/test_community_push.py, tests/logs/community_push/test_community_push/test_do_community_push_different_sharing_accounts.txt
This fixes a bug that when RHSM update is called and errors out. The old evolve wrote over all the data that was stored from the original upload. This protects the data from upload when an error occurs during the RHSM update step.
Related to: SPSTRAT-471
=> Fixes storing data in push_item when an error with rhsm happens.

setup.py
Changes:
- DeleteCommand: Use cloud_info data when available
- Bump starmap-client to v2.1.1
- Adds --repo-file, can be used to load info from a json file instead of string.
- Changes out repo-file from accepting json to accepting yaml files.
- Adds Azure support to delete command.
- Adds a wait for product to unlock to post-publish (AWS)
- Reverts from asyncio
- Gives Publish more threads to use while avoiding collision.
- Fixes storing data in push_item when an error with rhsm happens.
- Bump cloudpub to v1.3.0
=> Release v1.6.0

requirements.txt
Bump cloudpub to `v1.3.1` in order to fix the  missing alias for `dateOffset` on Azure
=> Bump cloudpub to v1.3.1

src/pubtools/_marketplacesvm/tasks/push/command.py, tests/combined_push/test_combined_push.py, tests/community_push/test_community_push.py, tests/push/test_push.py
This reverts the commit "Gives Publish more threads to use while avoiding collision."  2529f6f0a175b5423aa2c3ab408a0be507cd44fa.
There were 2 issues:
* images were published sequentially due to issue in logic SPSTRAT-516
* some push items were collected more times due to nested for loop SPSTRAT-515
I could fix both issues in the same PR. But I would like to get a feedback to the unit test.
=> Do not collect the same push_time more time

requirements.txt, src/pubtools/_marketplacesvm/cloud_providers/ms_azure.py, tests/cloud_providers/test_provider_azure.py
This commit changes the `AzureService._delete_push_images` to properly use the `AzureDeleteMetadata` from `cloudimg` which is the expected object for the library's `delete` parameter, instead of passing a dictionary.
Refers to SPSTRAT-571
=> SPSTRAT-571: Fix AzureService.delete method

setup.py
From PyPI:
```
This email is notifying you of an upcoming deprecation that we have determined may affect you as a result of your recent upload to 'pubtools-marketplacesvm'.
In the future, PyPI will require all newly uploaded source distribution filenames to comply with PEP 625. Any source distributions already uploaded will remain in place as-is and do not need to be updated.
Specifically, your recent upload of 'pubtools-marketplacesvm-1.8.0.tar.gz' is incompatible with PEP 625 because the filename does not contain the normalized project name 'pubtools_marketplacesvm'.
In most cases, this can be resolved by upgrading the version of your build tooling to a later version that supports PEP 625 and produces compliant filenames. You do not need to remove the file.
If you have questions, you …
```
=> Update package name to be compliant with PEP625
